// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class VotingscmTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void votingscm() {
    driver.get("http://localhost/scm/");
    driver.manage().window().setSize(new Dimension(1550, 830));
    driver.findElement(By.id("voterId")).click();
    driver.findElement(By.id("voterId")).sendKeys("Voting12");
    driver.findElement(By.id("voterPass")).click();
    driver.findElement(By.id("voterPass")).sendKeys("voter");
    driver.findElement(By.id("voterLoginBtn")).click();
    assertThat(driver.switchTo().alert().getText(), is("Login failed: Invalid credentials"));
    driver.findElement(By.id("voterId")).click();
    driver.findElement(By.id("voterId")).sendKeys("Voter");
    driver.findElement(By.id("voterId")).sendKeys("VOT1001");
    driver.findElement(By.id("voterPass")).sendKeys("pass123");
    driver.findElement(By.id("voterLoginBtn")).click();
    driver.findElement(By.id("logoutVoterBtn")).click();
  }
}
